Channels:
  - &InsuranceChannel
    Name: insurance-channel
    Consortium: InsuranceConsortium
    Application:
      Organizations:
        - InsurerOrg
        - ClientOrg
        - RegulatorOrg

  - &SOCChannel
    Name: soc-channel
    Consortium: SOCConsortium
    Application:
      Organizations:
        - SOCOrg

Consortiums:
  - &InsuranceConsortium
    Organizations:
      - InsurerOrg
      - ClientOrg
      - RegulatorOrg

  - &SOCConsortium
    Organizations:
      - SOCOrg